<?php

/** @var Products $block */

use Syedzaidi\JetIntegration\Block\Products;

foreach ($block->getProducts() as $item) {
    if(is_string($item) ) {
        echo $item . " <button onClick=\"window.location.reload();\">Generate Token</button>";
        break;
    }elseif (array_key_exists("merchant_sku", $item)) {
        echo sprintf("<b>Sku:</b> %s <b>status:</b> %s<br >", $item->merchant_sku, $item->status);
    }else {
        echo sprintf("<b>Sku:</b> %s <b>status:</b> Not found in Jet<br >", $item['sku_not_found']);
    }
}

echo "<hr>";
echo "<h1>Sending all product to Jet</h1>";
$block->sendCatalogToJet();
