<?php

/** @var Orders $block */

use Syedzaidi\JetIntegration\Block\Orders;

foreach ($block->jetOrderList() as $order) {
    echo $order->buyer->name;
}





echo <<<TAG
<div class="admin__data-grid-wrap">
    <table class="data-grid data-grid-draggable">
       <thead>
        <tr>
            <th class="data-grid-th _sortable _draggable">ID</th>
            <th class="data-grid-th _sortable _draggable">Name</th>
            <th class="data-grid-th _sortable _draggable">Phone</th>
            <th class="data-grid-th _sortable _draggable">Email</th>
            <th class="data-grid-th _sortable _draggable">Order Placed Date</th>
            <th class="data-grid-th _sortable _draggable">Status</th>
            <th class="data-grid-th _sortable _draggable">Merchant Order Id</th>
        </tr>
        </thead>
        <tbody>
TAG;

foreach ($block->jetOrderList() as $order){
    //echo $order->alt_order_id;
    echo '<tr class="data-row">'
             . '<td>'
             .   '<div class="data-grid-cell-content">'. "$order->alt_order_id" .'</div>'
             . '</td>'
        . '<td>'
        .   '<div class="data-grid-cell-content">'. $order->buyer->name .'</div>'
        . '</td>'
        . '<td>'
        .   '<div class="data-grid-cell-content">'. $order->buyer->phone_number .'</div>'
        . '</td>'
             . '<td>'
             .   '<div class="data-grid-cell-content">'. "$order->hash_email" .'</div>'
             . '</td>'
            . '<td>'
            .   '<div class="data-grid-cell-content">'. "$order->order_placed_date" .'</div>'
            . '</td>'
            . '<td>'
            .   '<div class="data-grid-cell-content">'. "$order->status" .'</div>'
            . '</td>'
            . '</td>'
            . '<td>'
            .   '<div class="data-grid-cell-content">'. "$order->merchant_order_id" .'</div>'
            . '</td>'
         . '</tr>';
}


echo "            
        </tbody>
    </table>
</div>";


echo "<h2>Check for Order Details:</h2>";
echo "<pre>";
print_r($block->ordersDetails("fc06533609ec4173acf9453d6dfc6492"));
