<?php

/** @var Orders $block */

use Syedzaidi\JetIntegration\Block\Orders;

echo "<h2>Check for Orders by Status:</h2>";
$block->ordersByStatus("ready"); // created, ready, acknowledged, inprogress and complete

//foreach ($block->getProducts() as $item) {
//    if(is_string($item) ) {
//        echo $item . " <button onClick=\"window.location.reload();\">Generate Token</button>";
//        break;
//    }elseif (array_key_exists("merchant_sku", $item)) {
//        echo sprintf("<b>Sku:</b> %s <b>status:</b> %s<br >", $item->merchant_sku, $item->status);
//    }else {
//        echo sprintf("<b>Sku:</b> %s <b>status:</b> Not found in Jet<br >", $item['sku_not_found']);
//    }
//}

echo "<h2>Check for Orders by Tagged:</h2>";
$block->ordersByTagged("ready", ""); // created, ready, acknowledged, inprogress and complete

//foreach ($block->getProducts() as $item) {
//    if(is_string($item) ) {
//        echo $item . " <button onClick=\"window.location.reload();\">Generate Token</button>";
//        break;
//    }elseif (array_key_exists("merchant_sku", $item)) {
//        echo sprintf("<b>Sku:</b> %s <b>status:</b> %s<br >", $item->merchant_sku, $item->status);
//    }else {
//        echo sprintf("<b>Sku:</b> %s <b>status:</b> Not found in Jet<br >", $item['sku_not_found']);
//    }
//}
