<?php

/** @var OrderView $block */

use Syedzaidi\JetIntegration\Block\OrderView;


echo <<<TAG
<div data-mage-init='{
    "collapsible":{
        "collapsible": true,
        "openedState": "active",
        "active": false
    }}' class="fieldset-wrapper admin__collapsible-block-wrapper">
    <div data-role="title" class="admin__collapsible-title">
        <h4>Current Row Jet Data</h4>
    </div>
    <div data-role="content">
TAG;

$singleorder = $block->jetOrderView();
if ($singleorder['jet_request_directed_cancel'] === true) {
    echo "<b>This order was canceled</b>";
}

echo "<pre>".json_encode($singleorder, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)."</pre>";

echo "</div></div>";


